-- DROP TABLE BOARD;

CREATE TABLE BOARD(
	IDX INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	CONTENTS VARCHAR(1000) NOT NULL,
	WRITER VARCHAR(100) NOT NULL,
	COUNT INT DEFAULT 0,
	INDATE DATETIME DEFAULT NOW(),
	
	PRIMARY KEY(IDX)
);

INSERT INTO BOARD(TITLE, CONTENTS, WRITER) 
	VALUES('나 의천인데 나만 다들 바라봤으면 좋겠다','내가 주인공이니까❤️','조의천');
INSERT INTO BOARD(TITLE, CONTENTS, WRITER) 
	VALUES('나 백승학','섹시한 팔뚝을 가지고있지','백승학');
INSERT INTO BOARD(TITLE, CONTENTS, WRITER) 
	VALUES('왜저래','다들 미친거임?','민현정');
	
COMMIT;
